source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'react-rails', '~> 1.3.0'
gem 'flux-rails-assets', '~> 2.1.0'
gem 'bcrypt', '~> 3.1.7'
gem 'paperclip', '~> 4.3'
gem 'figaro'
gem 'aws-sdk', '~> 1.6'
gem 'rename'
gem 'faker', '~> 1.5'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
end

group :production do
  gem 'rails_12factor'
end
